import type { Bindings } from '../worker/src/index';
import { apiWorker } from '../worker/src/index';
import { createUnifiedWorker } from '../worker/src/api-dispatch';

// OpenNext の build で生成され、Wrangler の bundle 時に解決される。
// @ts-ignore generated by opennextjs-cloudflare build
import nextWorker from './.open-next/worker.js';

export { BandDraftRoom } from '../worker/src/durable-objects/band-draft-room';
export { ReservationRoom } from '../worker/src/durable-objects/reservation-room';

export default createUnifiedWorker<Bindings>(nextWorker, apiWorker);
